#!/usr/bin/env bash
# Seed the two study actors and freeze the result as the golden content snapshot.
#
#   bash deploy/ghost/seed.sh            # no-op once the golden snapshot exists
#   GH_FORCE_SEED=1 bash .../seed.sh     # rebuild the golden snapshot
#
# Declared as docker_single.seed in fixtures/adapters/ghost_current_local.json, so
# docker_single_local runs it (a) once after `supervise` starts the container and
# (b) after every reset.  Case (b) must stay free: deploy/ghost/reset.sh restores
# the golden content directory, which already contains the seeded state, so the
# script returns immediately whenever the snapshot marker is present.
#
# Seed content is deliberately minimal - the two staff accounts plus whatever
# Ghost's own install fixtures create (the default posts, the default tag, the
# built-in theme).  Per-case preconditions are expressed as UI steps inside the
# recording workflows, so that they are recorded rather than preinstalled.
#
# actor_a is the installation OWNER, created through
#   POST /ghost/api/admin/authentication/setup/
# actor_b is a staff account created through the invitation flow.  Ghost has no
# API that returns the invitation token (it is only ever mailed), so the token is
# read straight out of the `invites` table of the instance's own SQLite file -
# we control the instance, and this replaces the out-of-band mailbox that
# ghost/core/test/e2e-browser would use.  The token is then redeemed through the
# public endpoint POST /ghost/api/admin/authentication/invitation/.
#
# Credentials never appear on a command line: every request body is generated by
# python3 from the environment and piped into curl.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=deploy/ghost/common.sh
. "$SCRIPT_DIR/common.sh"

if [ -f "$GOLDEN_MARKER" ] && [ "${GH_FORCE_SEED:-0}" != "1" ]; then
  exit 0
fi

require_env \
  UISEMTEST_GHOST_ACTOR_A_NAME UISEMTEST_GHOST_ACTOR_A_EMAIL UISEMTEST_GHOST_ACTOR_A_PASSWORD \
  UISEMTEST_GHOST_ACTOR_B_NAME UISEMTEST_GHOST_ACTOR_B_EMAIL UISEMTEST_GHOST_ACTOR_B_PASSWORD

SITE_TITLE="${UISEMTEST_GHOST_SITE_TITLE:-UISemTest Ghost}"
ACTOR_B_ROLE="${UISEMTEST_GHOST_ACTOR_B_ROLE:-Administrator}"

CONTAINER="$(resolve_container)"
wait_ready

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT
COOKIE_A="$WORK_DIR/actor_a.cookies"

json_body() {  # json_body <python expression building a dict from os.environ>
  python3 -c "$1"
}

post_json() {  # post_json <path> <cookie-jar-or-empty> <body-on-stdin>; echoes status
  local path="$1" jar="$2"
  if [ -n "$jar" ]; then
    curl -s -o "$WORK_DIR/resp.json" -w '%{http_code}' -X POST "$BASE_URL$path" \
      -H 'Content-Type: application/json' -H "Origin: $BASE_URL" \
      -b "$jar" -c "$jar" --data-binary @-
  else
    curl -s -o "$WORK_DIR/resp.json" -w '%{http_code}' -X POST "$BASE_URL$path" \
      -H 'Content-Type: application/json' -H "Origin: $BASE_URL" --data-binary @-
  fi
}

fail() { echo "ghost seed: $1" >&2; head -c 400 "$WORK_DIR/resp.json" >&2 2>/dev/null; echo >&2; exit 5; }

# ---------------------------------------------------------------- owner setup
status="$(json_body '
import json, os
print(json.dumps({"setup": [{
    "name": os.environ["UISEMTEST_GHOST_ACTOR_A_NAME"],
    "email": os.environ["UISEMTEST_GHOST_ACTOR_A_EMAIL"],
    "password": os.environ["UISEMTEST_GHOST_ACTOR_A_PASSWORD"],
    "blogTitle": os.environ.get("UISEMTEST_GHOST_SITE_TITLE", "UISemTest Ghost"),
}]}))' | post_json "/ghost/api/admin/authentication/setup/" "")"
[ "$status" = "201" ] || fail "owner setup returned $status"

# ------------------------------------------------------------ owner sign-in
status="$(json_body '
import json, os
print(json.dumps({
    "username": os.environ["UISEMTEST_GHOST_ACTOR_A_EMAIL"],
    "password": os.environ["UISEMTEST_GHOST_ACTOR_A_PASSWORD"],
}))' | post_json "/ghost/api/admin/session/" "$COOKIE_A")"
[ "$status" = "201" ] || fail "owner sign-in returned $status"

# ------------------------------------------------------------- staff invite
curl -fsS -b "$COOKIE_A" -H "Origin: $BASE_URL" \
  "$BASE_URL/ghost/api/admin/roles/?limit=all" -o "$WORK_DIR/roles.json" \
  || fail "roles read failed"
ROLE_ID="$(ROLES_FILE="$WORK_DIR/roles.json" ACTOR_B_ROLE="$ACTOR_B_ROLE" python3 -c '
import json, os, sys
roles = json.load(open(os.environ["ROLES_FILE"]))["roles"]
want = os.environ["ACTOR_B_ROLE"]
for role in roles:
    if role["name"] == want:
        print(role["id"])
        sys.exit(0)
sys.exit(1)
')"
[ -n "$ROLE_ID" ] || fail "role $ACTOR_B_ROLE not found"

status="$(ROLE_ID="$ROLE_ID" json_body '
import json, os
print(json.dumps({"invites": [{
    "role_id": os.environ["ROLE_ID"],
    "email": os.environ["UISEMTEST_GHOST_ACTOR_B_EMAIL"],
    "expires": None,
    "status": None,
    "token": None,
}]}))' | post_json "/ghost/api/admin/invites/" "$COOKIE_A")"
[ "$status" = "201" ] || fail "invite creation returned $status"

# The token is mailed, never returned; read it from the instance's own database.
TOKEN="$(sqlite3 "$DB_FILE" \
  "select token from invites where email = '$(printf '%s' "$UISEMTEST_GHOST_ACTOR_B_EMAIL" | sed "s/'/''/g")' order by created_at desc limit 1;")"
[ -n "$TOKEN" ] || fail "no invitation token found in the invites table"

status="$(GHOST_INVITE_TOKEN="$TOKEN" json_body '
import json, os
print(json.dumps({"invitation": [{
    "token": os.environ["GHOST_INVITE_TOKEN"],
    "email": os.environ["UISEMTEST_GHOST_ACTOR_B_EMAIL"],
    "name": os.environ["UISEMTEST_GHOST_ACTOR_B_NAME"],
    "password": os.environ["UISEMTEST_GHOST_ACTOR_B_PASSWORD"],
}]}))' | post_json "/ghost/api/admin/authentication/invitation/" "")"
[ "$status" = "200" ] || fail "invitation acceptance returned $status"

# ------------------------------------------------------------- verification
for actor in A B; do
  jar="$WORK_DIR/verify_$actor.cookies"
  status="$(ACTOR="$actor" json_body '
import json, os
a = os.environ["ACTOR"]
print(json.dumps({
    "username": os.environ["UISEMTEST_GHOST_ACTOR_%s_EMAIL" % a],
    "password": os.environ["UISEMTEST_GHOST_ACTOR_%s_PASSWORD" % a],
}))' | post_json "/ghost/api/admin/session/" "$jar")"
  [ "$status" = "201" ] || fail "verification sign-in for actor_$actor returned $status"
  probe="$(curl -s -o /dev/null -w '%{http_code}' -b "$jar" -H "Origin: $BASE_URL" \
    "$BASE_URL/ghost/api/admin/users/me/")"
  [ "$probe" = "200" ] || fail "identity probe for actor_$actor returned $probe"
done

# --------------------------------------------------------- golden snapshot
# Ghost keeps SQLite in journal_mode=delete (verified on this image), so a stopped
# server leaves a single self-contained database file and no -wal/-shm sidecars.
# The whole content directory is snapshotted because Ghost also keeps uploaded
# images, the routes.yaml settings file and the members key pair there.
docker stop -t 30 "$CONTAINER" >/dev/null
mkdir -p "$GOLDEN_DIR"
chmod -R u+w "$GOLDEN_DIR"
rsync -a --delete "$CONTENT_DIR/" "$GOLDEN_DIR/"
date -u +%Y-%m-%dT%H:%M:%SZ > "$GOLDEN_MARKER"
start_container_with_retry "$CONTAINER"
wait_ready

echo "ghost seed: golden snapshot written ($(find "$GOLDEN_DIR" -type f | wc -l | tr -d ' ') files, $(du -sk "$GOLDEN_DIR" | cut -f1) KiB)"
